export const CITY_LIST_REQUEST = "CITY_LIST_REQUEST";
export const CITY_LIST_SUCCESS = "CITY_LIST_SUCCESS";
export const CITY_LIST_FAIL = "CITY_LIST_FAIL";
export const CITY_WEATHER_ADD = "CITY_DETAILS_ADD";

export const CITY_WEATHER_REQUEST = "CITY_WEATHER_REQUEST";
export const CITY_WEATHER_SUCCESS = "CITY_WEATHER_SUCCESS";
export const CITY_WEATHER_FAIL = "CITY_WEATHER_FAIL";
